# Generated by Django 5.0.6 on 2024-07-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
