# Generated by Django 5.0.6 on 2024-07-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emergencycontact_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='chat_id',
        ),
    ]
