# Generated by Django 5.0.6 on 2024-07-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_emergencycontact_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
