# Generated by Django 5.0.6 on 2024-07-15 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
