# Generated by Django 5.0.6 on 2024-07-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
