# Generated by Django 5.0.6 on 2024-07-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_emergencycontact_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='latitude',
            field=models.FloatField(default=7.759904693656651),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='longitude',
            field=models.FloatField(default=4.601843448762301),
        ),
    ]
